name=input("enter the name:")
add=input("enter the address:")
email=input("enter the email:")
phone_no=int(input("enter the phone number:")
print("name is {} address is {} email is {} phone no is {}".format(name,add,email,phone_no))
